### ISSUE TITLE
Revise failure with KernelAbstractions

### ISSUE THREAD

**Issue by leios** [JuliaGPU/KernelAbstractions.jl#111]
I have been playing around with the following code:

```
module revise_tests
    export vadd

    using KernelAbstractions, CUDA
    if has_cuda_gpu()
        CUDA.allowscalar(false)
    end

    @kernel function vadd_kernel(c, a, b)

        cI = @index(Global)

        c[cI] = a[cI] + b[cI]
    end

    function vadd(c, a, b)
        if isa(c, Array)
            kernel! = vadd_kernel(CPU(), 8) 
        else
            kernel! = vadd_kernel(CUDADevice(),256)
        end
        kernel!(c, a, b, ndrange=size(c)) 
    end

end # module
```

If I do
```
julia> a = ones(100)
julia> c = zeros(100)
julia> revise_tests.vadd(c, a, a)
KernelAbstractions.CPUEvent(Task (done) @0x00007f673bfd2710)
```
`c` is correctly a set of 100 2s. If I modify the line above such that `c[cI] = a[cI] + b[cI]` is now `c[cI] = a[cI] + 2*b[cI]` (or somethign similar, I get the following error:

```
julia> revise_tests.vadd(c, a, a)
ERROR: MethodError: no method matching vadd_kernel(::KernelAbstractions.CPU, ::Int64)
Stacktrace:
 [1] vadd(::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at /home/leios/projects/revise_tests/src/revise_tests.jl:18
 [2] top-level scope at REPL[7]:1
 [3] run_backend(::REPL.REPLBackend) at /home/leios/.julia/packages/Revise/BqeJF/src/Revise.jl:1184
 [4] top-level scope at REPL[2]:0
```

As a note, changing the kernel names seems to be fine. If we `%s/vadd_kernel/check/g`, Revise does know the code is changed.

I don't mind poking around a bit, but do not really know where to look.

**Comment by vchuravy** [comment]
So we emit the kernels in https://github.com/JuliaGPU/KernelAbstractions.jl/blob/4ab11f29b615e72b5ec2112935593fb56309633a/src/macros.jl#L51-L63

What I suspect is happening is that Revise will delete a function, but the macro will not recreate it, because we check if the name has been defined before. I added that https://github.com/JuliaGPU/KernelAbstractions.jl/commit/2896ef745217ac37cc53be1dd296ca7f264e5f25 in order to allow two kernels to share the name.

@timholy any ideas how we can make macros defining functions compatible with revise?

**Comment by timholy** [comment]
I'm not sure I fully understand, but let me try: the macro expands to new definitions that run inside an `isdefined` check, and as a consequence it doesn't do anything if it re-evaluates. I'm not certain of the best way forward, but I'd consider maybe adding a `hasmethod` check to [this conditional](https://github.com/JuliaGPU/KernelAbstractions.jl/blob/4ab11f29b615e72b5ec2112935593fb56309633a/src/macros.jl#L52). That way, if Revise deletes the method then it should know that it needs to re-execute the block.

**Comment by vchuravy** [comment]
Ah that makes sense, the isdefined checks were for ensuring that one can
overload `@kernel` methods without getting redefined methods warning. We
can change that to `hasmethod` for Revise compatibility.

@leios do you want to give that a try?

**Comment by leios** [comment]
I am not really sure what happened between the opening of this issue and now, but I am unable to replicate this error with the provided code. Revise seems to work (at least in KA#master). For the record, I tried simple modifications of the provided module with dispatching on both the CPU and GPU.

For now, I will close this issue, but may re-open it in the future if the need arises.
