### ISSUE TITLE
What's going wrong when `kw.head != :kw` in @ka_code_typed?

### ISSUE THREAD

**Issue by glwagner** [JuliaGPU/KernelAbstractions.jl#143]
I'm hitting

https://github.com/JuliaGPU/KernelAbstractions.jl/blob/b19e0b7a70c77b0005a28b8245fb8e96b6cd1cf0/src/reflection.jl#L86

while trying to reflect on a relatively complicated kernel with `@ka_code_typed` --- but I don't know why and can't manage to hit the same error with a simple example.

**Comment by vchuravy** [comment]
@mjulian31 I suspect this might be something like `@ka_code_typed kernel(adapt(CuArra, data))`, e.g. an argument being a more complicated expression than just a reference.

**Comment by mjulian31** [comment]
@glwagner I am trying to duplicate this error- how are you calling @ka_code_typed? I was unable to duplicate the error with simpler calls that I thought might trigger the problem.

**Comment by mjulian31** [comment]
I think I have found and resolved the problem, see https://github.com/JuliaGPU/KernelAbstractions.jl/pull/144

**Comment by vchuravy** [comment]
Thanks!

**Comment by glwagner** [comment]
@mjulian31 sorry I didn't respond, I'm glad you could solve it despite my slowness! Thank you!
