### ISSUE TITLE
Buildkite: report separate statuses for Julia 1.5 and Julia nightly?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/KernelAbstractions.jl#156]
At first glance, it looks like Buildkite is failing.

For example, go to https://github.com/JuliaGPU/KernelAbstractions.jl/commits/master and click on the red :x: next to "vchuravy committed 4 days ago", and you see this:

So it seems that Buildkite is failing.

But then, if you click on "Details", it takes you to https://buildkite.com/julialang/kernelabstractions-dot-jl/builds/15, which shows that Buildkite passed on Julia 1.5 and failed on Julia nightly:

It's a little confusing to have this reported as a single status. Is there a way that we can configure Buildkite so that it reports two separate statuses, one for Julia 1.5 and one for Julia nightly?

cc: @maleadt @christopher-dg

**Comment by DilumAluthge** [comment]
See also this related issue: https://github.com/JuliaGPU/KernelAbstractions.jl/issues/158

**Comment by maleadt** [comment]
> if you click on "Details", it takes you to https://buildkite.com/julialang/kernelabstractions-dot-jl/builds/15, which shows that Buildkite passed on Julia 1.5 and failed on Julia nightly

So it did fail the run as a whole.

Anyway, I've enabled the setting that displays a status for each job. But ultimately, the run _did_ fail. If, for example, you put a `wait` and another job in the pipeline, it wouldn't run those because the entire has failed anyway.

**Comment by DilumAluthge** [comment]
> Anyway, I've enabled the setting that displays a status for each job.

Thanks!

**Comment by DilumAluthge** [comment]
> But ultimately, the run _did_ fail. If, for example, you put a `wait` and another job in the pipeline, it wouldn't run those because the entire has failed anyway.

Oh interesting. That's good to know.
