### ISSUE TITLE
How are the docs for this package being built and deployed?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/KernelAbstractions.jl#166]
The README currently has a "docs latest" button. If I click on this button, it brings me to the following URL: https://juliagpu.gitlab.io/KernelAbstractions.jl/

However, I don't see any CI jobs that push docs to GitLab.

And in fact, the `docs/make.jl` file does not have a call to `deploydocs`.

So, how are the docs for this package being built and deployed?

**Comment by vchuravy** [comment]
They used to be deployed through Gitlab, which allowed you to skip the deploydocs step.

**Comment by vchuravy** [comment]
Fixed by #167
