### ISSUE TITLE
Stop using Bors?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/KernelAbstractions.jl#189]
IIRC, the main motivation for Bors was to be able to run CI on PRs from forks.

Buildkite is able to run CI on PRs from forks.

So, if you want, we can get rid of Bors.

@vchuravy @maleadt Any thoughts?

**Comment by vchuravy** [comment]
I don't mind `bors` as much as other people seem to and enjoy doing a `bors r+` and then going along with my merry day.
But yes we used bors to overcome the technical limitation of Gitlab, so I would be okay with removing it.

**Comment by DilumAluthge** [comment]
Nah, if it works for your workflow, let's keep it.
