### ISSUE TITLE
Make the Bors status check required?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/KernelAbstractions.jl#194]
Right now, it's easy to accidentally merge a PR even when tests are failing.

The solution is relatively simple: just make the "bors" status check a "required status check" in the repository settings.

@vchuravy @maleadt Does this sound reasonable?

**Comment by vchuravy** [comment]
I think I just done that

**Comment by DilumAluthge** [comment]
Yep, looks good!

![9536BB8C-FC8F-477D-802B-17A6A0ABCE0B](https://user-images.githubusercontent.com/5619885/104073952-f4675600-51dc-11eb-8b7a-51fdbafb2856.jpeg)
