### ISSUE TITLE
Feature request: performant matmul! example

### ISSUE THREAD

**Issue by piever** [JuliaGPU/KernelAbstractions.jl#205]
I've noticed that `transpose` and `copy` are implemented in both a naive and a performant way [here](https://juliagpu.github.io/KernelAbstractions.jl/dev/examples/performance/). On the other hand, for `matmul!`, I could only find the naive implementation [here](https://juliagpu.github.io/KernelAbstractions.jl/dev/examples/matmul/).

I understand that a performant julia `matmul!` on the GPU is a whole research project on its own over at [GemmKernels.jl](https://github.com/JuliaGPU/GemmKernels.jl), but I was curious whether there would be some "middle ground" that loses some performance compared to cuBLAS but is easy and general. IMO, a good endgoal would be to be able to generate that code from a DSL like Tullio (see https://github.com/mcabbott/Tullio.jl/issues/80#issuecomment-770614929).

**Comment by vchuravy** [comment]
@mjulian31 can you add your better matmul code as an example?

**Comment by DilumAluthge** [comment]
BTW, once we have a performant matmul example, it would be great to add it to the benchmark comparisons in [BLASBenchmarksGPU.jl](https://github.com/JuliaLinearAlgebra/BLASBenchmarksGPU.jl).
