### ISSUE TITLE
TODO: code coverage for the `/lib/CUDAKernels/src/` folder

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/KernelAbstractions.jl#213]
Currently, Codecov is only showing coverage for source files in the `/src/` folder:
- https://codecov.io/gh/JuliaGPU/KernelAbstractions.jl

We should figure out how to also submit coverage information to Codecov for source files in the `/lib/CUDAKernels/src` folder.

**Comment by DilumAluthge** [comment]
@maleadt Is this possible with [julia-coverage-buildkite-plugin](https://github.com/JuliaCI/julia-coverage-buildkite-plugin)?

**Comment by maleadt** [comment]
Yes: https://github.com/JuliaGPU/CUDA.jl/blob/597603acd266c8e57031a426a6b818952fff6e43/.buildkite/pipeline.yml#L10-L15.

**Comment by DilumAluthge** [comment]
Thanks @maleadt!

Fixed by https://github.com/JuliaGPU/KernelAbstractions.jl/pull/214.

Here's a screenshot of https://codecov.io/gh/JuliaGPU/KernelAbstractions.jl:

![Screen Shot 2021-02-15 at 06 26 00](https://user-images.githubusercontent.com/5619885/107940814-d668e000-6f56-11eb-873f-c914c3cde604.png)
