### ISSUE TITLE
InvalidIRError when using integer powers

### ISSUE THREAD

**Issue by sandreza** [JuliaGPU/KernelAbstractions.jl#223]
It seems that using integer powers as in 2^11 in a kernel yields an error 

MWE: 
In https://github.com/JuliaGPU/KernelAbstractions.jl/blob/master/examples/matmul.jl#L10
If one instead adds m=2^11 to line 10
```julia
@kernel function matmul_kernel!(a, b, c)
    i, j = @index(Global, NTuple)
    m = 2^11
    # creating a temporary sum variable for matrix multiplication
    tmp_sum = zero(eltype(c))
    for k = 1:size(a)[2]
        tmp_sum += a[i,k] * b[k, j]
    end

    c[i,j] = tmp_sum
end
```
one gets an invalid IRE error: 
<img width="970" alt="Screen Shot 2021-03-20 at 7 17 14 PM" src="https://user-images.githubusercontent.com/22668662/111888216-ed18b180-89b0-11eb-8b60-96ec53a2c98d.png">

  However, change m = 2^11 to m = Int(2.0^11), as in
  ```julia
@kernel function matmul_kernel!(a, b, c)
    i, j = @index(Global, NTuple)
    m = Int(2.0^11)
    # creating a temporary sum variable for matrix multiplication
    tmp_sum = zero(eltype(c))
    for k = 1:size(a)[2]
        tmp_sum += a[i,k] * b[k, j]
    end

    c[i,j] = tmp_sum
end
```
yields no error and the test passes.

Perhaps extending https://github.com/JuliaGPU/KernelAbstractions.jl/blob/e08b87dd6e89797afda2c4cf8a0c8ad4941e8a9a/lib/CUDAKernels/src/CUDAKernels.jl#L281-L285 to integers solves the issue?

Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, cascadelake)
  
  The GPU is a TitanV

**Comment by DilumAluthge** [comment]
Does CUDA have an intrinsic for raising an integer base to an integer power? I don't see it here (https://docs.nvidia.com/cuda/cuda-math-api/index.html#group__CUDA__MATH__DOUBLE_1g6d36757715384dc18e0483aa1f04f6c7) or here (https://github.com/JuliaGPU/CUDA.jl/blob/master/src/device/intrinsics/math.jl).

**Comment by chriselrod** [comment]
I assume `1 << 11` works?
Of course, that only works for powers of 2.

**Comment by sandreza** [comment]
Indeed 1 << 11 works! Thank you for this solution @chriselrod

**Comment by jkozdon** [comment]
I think that it is the compiler failing to expand for above powers of `8`.

For `2^8` the compiler optimizes to the constant `256`
```
julia> function foo()
          m = 2^8
       end
foo (generic function with 1 method)

julia> @code_llvm foo()

;  @ REPL[49]:1 within `foo'
define i64 @julia_foo_494() {
top:
;  @ REPL[49]:2 within `foo'
  ret i64 256
}
```

But for `2^9` the compiler doesn't generate the constant value
```
julia> function bar()
          m = 2^9
       end
bar (generic function with 1 method)

julia> @code_llvm bar()

;  @ REPL[51]:1 within `bar'
define i64 @julia_bar_502() {
L21.lr.ph:
;  @ REPL[51]:2 within `bar'
; ┌ @ none within `literal_pow'
; │┌ @ none within `macro expansion'
; ││┌ @ intfuncs.jl:273 within `^'
; │││┌ @ intfuncs.jl:260 within `power_by_squaring'
      br label %L21

L21:                                              ; preds = %L21, %L21.lr.ph
      %0 = phi i64 [ 2, %L21.lr.ph ], [ %2, %L21 ]
      %value_phi35 = phi i64 [ 2, %L21.lr.ph ], [ %1, %L21 ]
; ││││ @ intfuncs.jl:261 within `power_by_squaring'
; ││││┌ @ int.jl:87 within `*'
       %1 = mul i64 %value_phi35, %value_phi35
; ││││└
; ││││ @ intfuncs.jl:260 within `power_by_squaring'
; ││││┌ @ int.jl:85 within `-'
       %2 = add nsw i64 %0, -1
; ││││└
; ││││┌ @ operators.jl:350 within `>='
; │││││┌ @ int.jl:441 within `<='
        %3 = icmp slt i64 %0, 1
; ││││└└
      br i1 %3, label %L23, label %L21

L23:                                              ; preds = %L21
; ││││ @ intfuncs.jl:261 within `power_by_squaring'
; ││││┌ @ int.jl:87 within `*'
       %.lcssa = phi i64 [ %1, %L21 ]
; ││││└
; ││││ @ intfuncs.jl:260 within `power_by_squaring'
      %phitmp = shl i64 %.lcssa, 1
; └└└└
  ret i64 %phitmp
}
```

**Comment by sandreza** [comment]
closing due to #224
