### ISSUE TITLE
Julia compat entry

### ISSUE THREAD

**Issue by tomchor** [JuliaGPU/KernelAbstractions.jl#238]
Hello, this may be a naive question but is there a reason why the Julia compat entry is listed as 1.3? 

https://github.com/JuliaGPU/KernelAbstractions.jl/blob/ace889168f4273e4efbabdfbd1317147c05116b4/Project.toml#L21

Thanks!

**Comment by chriselrod** [comment]
This is when [Threads.@spawn](https://github.com/JuliaGPU/KernelAbstractions.jl/blob/ace889168f4273e4efbabdfbd1317147c05116b4/src/cpu.jl#L133) was added.

**Comment by tomchor** [comment]
Thanks for the prompt reply! sorry for not being very clear, but I guess my question was more along the lines of: shouldn't the entry be something like `julia = "^1.3"`?

**Comment by chriselrod** [comment]
The `^` is unnecessary; it is the default:

> Caret specifiers are the default and hence `1.2.3 == ^1.2.3`.

https://pkgdocs.julialang.org/v1/compatibility/#Version-specifier-format

**Comment by tomchor** [comment]
Alright, I didn't know that! Thanks!
