### ISSUE TITLE
Auto-inbounds and nothing?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaGPU/KernelAbstractions.jl#240]
A lot of the DiffEqGPU code needs to look like:

```julia
function lorenz(du,u,p,t)
 @inbounds begin
     du[1] = p[1]*(u[2]-u[1])
     du[2] = u[1]*(p[2]-u[3]) - u[2]
     du[3] = u[1]*u[2] - p[3]*u[3]
 end
 nothing
end
```

I was wondering if `@kernel`'s context handling could somehow modify functions to do this automatically, so that a standard DiffEq function:

```julia
function lorenz(du,u,p,t)
   du[1] = p[1]*(u[2]-u[1])
   du[2] = u[1]*(p[2]-u[3]) - u[2]
   du[3] = u[1]*u[2] - p[3]*u[3]
end
```

could work just fine.

**Comment by vchuravy** [comment]
KernelAbstractions does insert a `nothing` into the kernel itself. What is the error you get when you remove that from these functions?

**Comment by ChrisRackauckas** [comment]
oh and it seems to propagate inbounds too now? Awesome.
