### ISSUE TITLE
CUDADevice not defined

### ISSUE THREAD

**Issue by torrance** [JuliaGPU/KernelAbstractions.jl#296]
I am unable to port my kernels to use KernelAbstraction.jl since CUDADevice is not defined after importing. eg.

    using CUDA
    using KernelAbstractions

    CUDA.functional()
    > true

    device = CUDADevice()
    > ERROR: UndefVarError: CUDADevice not defined

Note that CUDA works just fine. The versions I am currently using are: CUDA: 3.8.1 and KernelAbstractions: 0.8.0

**Comment by vchuravy** [comment]
You need to import CUDAKernels which contains the CUDA implementation of KernelAbstractions

**Comment by torrance** [comment]
Ok thank you. Should the documentation be updated to reflect this?

**Comment by torrance** [comment]
(It's not obvious in the docs that examples/utils.jl is importing this.

**Comment by bjarthur** [comment]
`using CUDAKernels` is on line 4 of examples/utils.jl:  https://github.com/JuliaGPU/KernelAbstractions.jl/blob/master/examples/utils.jl#L4

it is also mentioned in the docs:  https://github.com/JuliaGPU/KernelAbstractions.jl/blob/master/docs/src/index.md?plain=1#L57

**Comment by stemann** [comment]
Allegedly fixed according to https://github.com/JuliaGPU/KernelAbstractions.jl/pull/314#issuecomment-1182995831
