### ISSUE TITLE
Add Metal support

### ISSUE THREAD

**Issue by ViralBShah** [JuliaGPU/KernelAbstractions.jl#326]
As the M1 GPUs are becoming popular, it would be great to add Metal support to KernelAbstractions.jl. 

cc @maleadt

**Comment by bjarthur** [comment]
worth noting that at 128GB unified memory the mac studio has the largest VRAM of any vendor.

**Comment by garymm** [comment]
I guess this should be noted in the README, which lists supported backends but does not mention Metal

**Comment by ViralBShah** [comment]
Submit a PR to the README?
