### ISSUE TITLE
Support for single-threaded kernels even when `Threads.nthreads() != 1`?

### ISSUE THREAD

**Issue by glwagner** [JuliaGPU/KernelAbstractions.jl#328]
Occasionally we have applications that could benefit from multithreading, but in which it's better to divide the computation at a higher-level than a kernel. In that case, we need to launch julia with multiple threads, but have the capacity to launch a KA loop on just one thread. I guess such an API would essentially generalize

https://github.com/JuliaGPU/KernelAbstractions.jl/blob/67122c18bb619bd5e2c04689761ce8c5cefa54b4/src/cpu.jl#L118

to something that could be controlled at kernel launch time.

cc @simone-silvestri @navidcy

**Comment by vchuravy** [comment]
Hm, generally not a fan of that kind of device specific control. You could set `workgroupsize = ndrange` on launch to get this effect, but generally speaking Julia task-scheduler should do the load-balancing for you.

**Comment by vchuravy** [comment]
To maybe be a bit more specific, I feel for those kind of usages it is probably better to just use a `map` in Julia, instead of writting a KA kernel.

**Comment by glwagner** [comment]
> generally speaking Julia task-scheduler should do the load-balancing for you.

This is a fair point. I think I can close this because it's not pressing, really.

But for historical purposes let me clarify the problem I have. Say I have a function `lots_of_kernels!(model)` that itself involves many KA kernels. We wrote our code this way because our problems are typically huge (eg Oceananigans). But sometimes (doh!) we want to run hundreds, thousands, or even millions of tiny problems instead.

Then I need to do something like

```julia
for i = 1:huge
    lots_of_kernels!(models[i])
end
```

But presumably it'd be more performant to do

```julia
Threads.@threads for i = 1:huge
    lots_of_kernels!(models[i], nthreads=1)
end
```

then each invocation of `lots_of_kernels!` uses just one thread, and I can move my parallelization a bit further outwards.

**Comment by vchuravy** [comment]
Parallelization in Julia is composable, so generally you have not to worry about it to much.

The thing you should do is choose your `workgroupsize` appropriately. We create a task per workgroup. So if you make them large we generate a few tasks if you make it very small we generate many tasks.
