### ISSUE TITLE
Render issue with Docs admonition?

### ISSUE THREAD

**Issue by navidcy** [JuliaGPU/KernelAbstractions.jl#332]
Are these lines here supposed to be in the admonition?

https://github.com/JuliaGPU/KernelAbstractions.jl/blob/2c67ba27578d2f3c4e38722fe103043e7ae5f442/docs/src/index.md#L15-L18

<img width="980" alt="Screen Shot 2022-11-17 at 9 22 06 am" src="https://user-images.githubusercontent.com/7112768/202307307-19fbf04c-3363-44a2-bc9d-cca92e26e44c.png">

**Comment by vchuravy** [comment]
Yeah I think it is missing indentation.
