### ISSUE TITLE
`CPU(static=true)` option

### ISSUE THREAD

**Issue by carstenbauer** [JuliaGPU/KernelAbstractions.jl#387]
I think it would be valuable to add a `CPU(static=true)` option to the `CPU` backend that runs a kernel with `@threads :static` instead of `@spawn`. `CPU(static=false)` could still be the default such that this would be non-breaking.

On multi-NUMA domain systems it is crucial to make sure that pages get established on the correct NUMA node. Pragmatically, this may be realized by first-touch policy, i.e. initializing the data in parallel via `@threads :static` ([example](https://github.com/JuliaPerf/STREAMBenchmark.jl/blob/master/src/benchmarks.jl#L38-L61)). However, ideally, the kernel must also use the same threads to access the same pieces of the data to run efficiently. Because KA.jl is currently using `@spawn`, it is non-deterministic on which thread tasks might end up running on and consequently one gets subpar performance (even worse, it can fluctuate heavily).

(cc @vchuravy)

**Comment by vchuravy** [comment]
I will trade you implement this for a good example/documentation on how to use KA with NUMA aware code.

**Comment by vchuravy** [comment]
> If such an example plus a description of what is going on / why this is necessary is good enough, we have a deal wink

Yes!

Yeah we could make these https://github.com/JuliaGPU/KernelAbstractions.jl/blob/edaa0242dbedc3f57f46729aacb7546a1ac6a33d/src/cpu.jl#L7-L8 use `static=true`.

**Comment by carstenbauer** [comment]
Xref: https://github.com/JuliaGPU/KernelAbstractions.jl/pull/388

**Comment by navidcy** [comment]
Was this resolved by #388?
