### ISSUE TITLE
Integrate `async_copy!` into the event system

### ISSUE THREAD

**Issue by vchuravy** [JuliaGPU/KernelAbstractions.jl#40]
The code from https://github.com/climate-machine/CLIMA/blob/ad0508d7c0fa1004552197bb32334cfe923dd6ba/src/Arrays/CMBuffers.jl#L124-L209 needs to be integrated into KA and especially into the KA event system.

**Comment by lcw** [comment]
That would be useful.  I created something like this
https://github.com/lcw/Heptapus.jl/blob/d7dfa1debbf4ec564321b29a87c17eb304c00c46/examples/mpika/try.jl#L37-L52
but it would be nice if it was in KA.

**Comment by vchuravy** [comment]
Right it also needs to use one of the KA streams :)

**Comment by vchuravy** [comment]
This is done!
