### ISSUE TITLE
MAX support?

### ISSUE THREAD

**Issue by ManuelCostanzo** [JuliaGPU/KernelAbstractions.jl#460]
Hi! Thank you very much for this project.

I'm working on a kernel where I need to do a "max". For example

`a = max(1,2)
`
But I'm getting this error: 

```
Reason: unsupported call to an unknown function (call to julia.new_gc_frame)
Reason: unsupported call to an unknown function (call to julia.push_gc_frame)
Reason: unsupported call to an unknown function (call to julia.get_gc_frame_slot)
Reason: unsupported dynamic function invocation
```

There is no support for max? Thank you!

**Comment by vchuravy** [comment]
Can you share a MWE?

**Comment by ManuelCostanzo** [comment]
I'm sorry! I had a type in a variable. Is working fine, thank you
