### ISSUE TITLE
Cannot resolve isbits when using function call to isbits

### ISSUE THREAD

**Issue by charleskawczynski** [JuliaGPU/KernelAbstractions.jl#79]
This might be more of a question than an issue. [This commit](https://github.com/climate-machine/CLIMA/commit/9ebcd8955d83d722fed05722069bfac830afcbdb) seems to fix running [Dycoms](https://github.com/climate-machine/CLIMA/blob/ck/KernelAbstractionInference/experiments/AtmosLES/dycoms.jl) on the GPU, otherwise an isbits error is thrown. Is this the expected behavior?

**Comment by vchuravy** [comment]
Do you have the precise error at hand?

**Comment by charleskawczynski** [comment]
Yep, [here](https://gist.github.com/charleskawczynski/76588e7fd0bf0fb3fcea178e73d02adf)

**Comment by vchuravy** [comment]
`var"#5#8"{DataType,Float64}` this would need to read as `var"#5#8"{Type{Float64},Float64}` so yeah that closure is not legal on the GPU and is mostly due to the fact that Julia perceives to be non-const. It seems it is a global and not passed in to the function?

**Comment by charleskawczynski** [comment]
Agreed, but I'm not exactly sure why that commit would change things, it's just adding a pointer to the same data, right? The method inclusion and `param_set` definition are [here](https://github.com/climate-machine/CLIMA/blob/ck/KernelAbstractionInference/experiments/AtmosLES/dycoms.jl#L22-L25) and the method is defined [here](https://github.com/climate-machine/CLIMA/blob/ck/KernelAbstractionInference/Parameters/Planet.jl#L32). So, I'd think that the compiler should be able to infer that it's a constant, but yes, the `param_set` is global. I think I tried using `const param_set = ParameterSet()`, but this didn't fix the problem. That's when I tried [pulling `param_set` out of `PrescribedMoistureFlux`](https://github.com/climate-machine/CLIMA/commit/9ebcd8955d83d722fed05722069bfac830afcbdb#diff-bfa27a1e2ff249a3692ffa798a990eceR291-R314).

Just to reiterate, I'm not sure if this is a bug or expected behavior.

**Comment by vchuravy** [comment]
This sounds like expected behavior. The global can't be statically inferred. You could try
```
let param_set=param_set
  model = AtmosModel{FT}(
        AtmosLESConfigType;
        ref_state = ref_state,
        turbulence = SmagorinskyLilly{FT}(C_smag),
        moisture = EquilMoist{FT}(; maxiter = 5),
        radiation = radiation,
        source = source,
        boundarycondition = (
            AtmosBC(
                momentum = Impenetrable(DragLaw(
                    (state, aux, t, normPu) -> C_drag,
                )),
                energy = PrescribedEnergyFlux((state, aux, t) -> LHF + SHF),
                moisture = PrescribedMoistureFlux(
                    (state, aux, t) -> LHF / FT(LH_v0(param_set)),
                    (state, aux, t) -> moisture_flux,
                ),
....
```

**Comment by vchuravy** [comment]
Let me know on Slack if you have more questions.
