### ISSUE TITLE
Defining the same function twice? Maybe a typo?

### ISSUE THREAD

**Issue by GiggleLiu** [JuliaGPU/KernelAbstractions.jl#93]
Line 53 and line 54 looks like the same function defined twice. It keeps warning me, is this a typo? or maybe not?

https://github.com/JuliaGPU/KernelAbstractions.jl/blob/dd93c7abed46b53d89e8368ca747af8e616c5489/src/macros.jl#L53

**Comment by vchuravy** [comment]
That looks like a merge or rebase error. The second line was added in https://github.com/JuliaGPU/KernelAbstractions.jl/commit/89b3f0abaf8652a71d2e4d9df099d3b319ef76d8
